// <auto-generated />
namespace FIT5032_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _123ad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123ad));
        
        string IMigrationMetadata.Id
        {
            get { return "202310210308395_123ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
