// <auto-generated />
namespace FIT5032_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imgggg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imgggg));
        
        string IMigrationMetadata.Id
        {
            get { return "202310111748261_imgggg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
